name:                bookdownlight
version:             0.1.0.0
github:              "scmu/bookdownlight"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bookdownlight#readme>

dependencies:
- base >=4.9 && <5
#- binary
- bytestring
- containers >=0.4 && <0.7
- mtl # >=2.1 && <2.3
- text # >= 0.9 && < 1.3
#- blaze-html # >=0.6 && < 0.10
#- xss-sanitize >= 0.3 && < 0.4
- data-default # >= 0.5 && < 0.8
- syb
- uniplate >= 1.6 && < 1.7
- deepseq
- bytestring
- directory
- shake
- time
#- text-icu
#- text-regex-replace
- text-replace
#- megaparsec
#- parser-combinators
#- replace-megaparsec
- regex-tdfa

extra-lib-dirs:
- /opt/homebrew/opt/icu4c/lib/

extra-include-dirs:
- /opt/homebrew/opt/icu4c/include/

library:
  source-dirs: src

executables:
  bookdownlight-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bookdownlight
